state_space_graph = {
    "Asmera": [("Axum",5), ("Adigrat",6)],
    "Axum": [("Asmera",5), ("Shire",2), ("Adwa",1)],
    "Kartum": [("Humera",21), ("Metema",19)],
    "Shire": [("Humera",8), ("Axum",2), ("Debarke",7)],
    "Humera": [("Shire",8), ("Gondar",9), ("Kartum",21)],
    "Metema": [("Gondar",7), ("Kartum",19), ("Azezo",7)],
    "Debarke": [("Shire",7), ("Gondar",4)],
    "Adigrat": [("Asmera",6), ("Adwa",4), ("Mekelle",4)],
    "Adwa": [("Adigrat",4), ("Axum",1), ("Mekelle",7)],
    "Mekelle": [("Adigrat",4), ("Adwa",7), ("Sekota",9), ("Alamata",5)],
    "Alamata": [("Mekelle",5), ("Sekota",6), ("Samara",11), ("Woldia",3)],
    "Kilbet Rasu": [("Fanti Rasu",6)],
    "Fanti Rasu": [("Kilbet Rasu",6), ("Samara",7)],
    "Samara": [("Fanti Rasu",7), ("Alamata",11), ("Woldia",8), ("Gabi Rasu",9)],
    "Gondar": [("Debarke",4), ("Metema",7), ("Humera",9), ("Azezo",1)],
    "Sekota": [("Mekelle",9), ("Alamata",6), ("Lalibela",6)],
    "Azezo": [("Gondar",1), ("Metema",7), ("Bahir Dar",7)],
    "Debre Tabor": [("Bahir Dar",4), ("Lalibela",8)],
    "Lalibela": [("Sekota",6), ("Woldia",7), ("Debre Tabor",8)],
    "Woldia": [("Lalibela",7), ("Dessie",6), ("Alamata",3), ("Samara",8)],
    "Bahir Dar": [("Metekel",11), ("Debre Tabor",4), ("Injibara",4), ("Finote Selam",6), ("Azezo",7)],
    "Dessie": [("Woldia",6), ("Kemise",4)],
    "Debre Sina": [("Kemise",6), ("Debre Birhan",2), ("Debre Markos",17)],
    "Debre Markos": [("Debre Sina",17), ("Finote Selam",3)],
    "Kemise": [("Dessie",4), ("Debre Sina",6)],
    "Finote Selam": [("Debre Markos",3), ("Bahir Dar",6), ("Injibara",2)],
    "Injibara": [("Finote Selam",2), ("Bahir Dar",4)],
    "Metekel": [("Bahir Dar",11)],
    "Gabi Rasu": [("Samara",9), ("Awash",5)],
    "Debre Birhan": [("Debre Sina",2), ("Addis Ababa",5)],
    "Addis Ababa": [("Debre Birhan",5), ("Ambo",5), ("Adama",3)],
    "Adama": [("Addis Ababa",3), ("Batu",4), ("Assella",4), ("Matahara",3)],
    "Assosa": [("Dembi Dollo",12)],
    "Dembi Dollo": [("Assosa",12), ("Gambella",4), ("Gimbi",6)],
    "Gimbi": [("Dembi Dollo",6), ("Nekemete",4)],
    "Nekemete": [("Gimbi",4), ("Ambo",9), ("Bedelle", 4)],
    "Ambo": [("Addis Ababa",5), ("Nekemete",9), ("Wolkite",6)],
    "Matahara": [("Adama",3), ("Awash",1)],
    "Awash": [("Matahara",1), ("Chiro",4), ("Gabi Rasu", 5)],
    "Chiro": [("Awash",4), ("Dire Dawa",8)],
    "Dire Dawa": [("Chiro",8), ("Harar",4)],
    "Harar": [("Dire Dawa",4), ("Babile",2)],
    "Babile": [("Harar",2), ("Jigjiga",3), ("Goba", 28)],
    "Jigjiga": [("Babile",3), ("Dega Habur",5)],
    "Dega Habur": [("Jigjiga",5), ("Kebri Dehar",6)],
    "Kebri Dehar": [("Gode",5), ("Werder",6), ("Dega Habur",6)],
    "Werder": [("Kebri Dehar",6)],
    "Gode": [("Mokadisho",22), ("Kebri Dehar",5), ("Dollo",17), ("Sof Oumer", 23)],
    "Dollo": [("Gode",17)],
    "Mokadisho": [("Gode",22)],
    "Gambella": [("Gore",5), ("Dembi Dollo",4)],
    "Gore": [("Gambella",5), ("Tepi",9), ("Bedelle",6)],
    "Bedelle": [("Gore",6), ("Jimma",7), ("Nekemete",4)],
    "Tepi": [("Gore",9), ("Bonga",8), ("Mezan Teferi",4)],
    "Mezan Teferi": [("Bonga",4), ("Tepi",4)],
    "Bonga": [("Mezan Teferi",4), ("Jimma",4), ("Dawro",10), ("Tepi",8)],
    "Dawro": [("Bonga",10), ("Wolaita Sodo",6)],
    "Basketo": [("Bench Maji",5), ("Arba Minch",10)],
    "Bench Maji": [("Basketo",5), ("Juba",22)],
    "Juba": [("Bench Maji",22)],
    "Arba Minch": [("Konso",4), ("Basketo",10), ("Wolaita Soda",4)],
    "Konso": [("Arba Minch",4), ("Yabello",3)],
    "Yabello": [("Konso",3), ("Bule Hora",3), ("Moyale",6)],
    "Moyale": [("Yabello",6), ("Nairobi",22)],
    "Nairobi": [("Moyale",22)],
    "Bule Hora": [("Dilla",4), ("Yabello",3)],
    "Dilla": [("Bule Hora",4), ("Hawassa",3)],
    "Hawassa": [("Dilla",3), ("Shashemene",1)],
    "Jimma": [("Bonga",4), ("Wolkite",8), ("Bedelle",7)],
    "Wolkite": [("Jimma",8), ("Ambo",6), ("Worabe",5)],
    "Worabe": [("Wolkite",5), ("Buta Jirra",2), ("Hossana",2)],
    "Hossana": [("Worabe",2), ("Wolaita Sodo",4), ("Shashemene",7)],
    "Wolaita Sodo": [("Hossana",4), ("Dawro",6), ("Arba Minch", 4)],
    "Buta Jirra": [("Worabe",2), ("Batu",2)],
    "Batu": [("Buta Jirra",2), ("Shashemene",3), ("Adama",4)],
    "Shashemene": [("Batu",3), ("Hossana",7), ("Dodolla",3), ("Hawassa",1)],
    "Assella": [("Adama",4), ("Assasa",4)],
    "Assasa": [("Assella",4), ("Dodolla",1)],
    "Dodolla": [("Assasa",1), ("Bale",13), ("Shashemene",3)],
    "Bale": [("Dodolla",13), ("Goba",18), ("Liben",11), ("Sof Oumer",23)],
    "Goba": [("Babile",28), ("Sof Oumer",6), ("Bale",18)],
    "Sof Oumer": [("Goba",6), ("Bale",23), ("Gode",23)],
    "Liben": [("Bale",11)],
}