# Define the state space graph as per the image and count the cities
state_space_graph = {
    "Asmara": ["Adigrat", "Axum"],
    "Adigrat": ["Axum", "Adwa", "Asmara"],
    "Axum": ["Adigrat", "Adwa", "Shire"],
    "Shire": ["Axum", "Humera", "Debark"],
    "Humera": ["Shire", "Kartum", "Gondar"],
    "Adwa": ["Axum", "Adigrat", "Mekelle"],
    "Kartum": ["Humera", "Metema"],
    "Metema": ["Azezo", "Gondar", "Kartum"],
    "Debark": ["Shire", "Gondar"],
    "Gondar": ["Debark", "Azezo", "Metema", "Humera"],
    "Mekelle": ["Adwa", "Adigrat", "Sekota", "Alamata"],
    "Sekota": ["Lalibela", "Mekelle", "Alamata"],
    "Kilbet Rasu": ["Fanti Rasu"],
    "Fanti Rasu": ["Semera"],
    "Alamata": ["Sekota", "Mekelle", "Woldiya", "Samara"],
    "Azezo": ["Gondar", "Metema", "Bahir Dar"],
    "Debre Tabor": ["Bahir Dar", "Lalibela"],
    "Samara": ["Fanti Rasu", "Alamata", "Woldia", "Gabi Rasu"],
    "Bahir Dar": ["Azezo", "Debre Tabor", "Finote Selam", "Metekel", "Injibara"],
    "Woldia": ["Dessie", "Lalibela", "Alamata", "Samara"],
    "Lalibela": ["Woldia", "Sekota", "Debre Tabor"],
    "Metekel": ["Assosa", "Bahir Dar"],
    "Dessie": ["Kemise", "Woldia"],
    "Finote Selam": ["Injibara", "Bahir Dar", "Debre Markos"],
    "Kemise": ["Debre Sina", "Dessie"],
    "Injibara": ["Bahir Dar", "Finote Selam"],
    "Gabi Rasu": ["Semera", "Awash"],
    "Debre Sina": ["Debre Markos", "Kemise", "Debre Birhan"],
    "Debre Markos": ["Finote Selam", "Debre Sina"],
    "Asosa": ["Metekel", "Dembi Dollo"],
    "Debre Birhan": ["Addis Ababa", "Debre Sina"],
    "Dire Dawa": ["Chiro", "Harar"],
    "Chiro": ["Awash", "Dire Dawa"],
    "Harar": ["Dire Dawa", "Babile"],
    "Babile": ["Harar", "Jigjiga"],
    "Jigjiga": ["Babile", "Dega Habur"],
    "Gimbi": ["Dembi Dollo", "Bedelle", "Ambo"],
    "Nekemte": ["Gimbi", "Finote Selam"],
    "Addis Ababa": ["Debre Birhan", "Ambo", "Adama"],
    "Ambo": ["Addis Ababa", "Wolkite", "Nekemte"],
    "Awash": ["Chiro", "Matahara", "Gabi Rasu"],
    "Dembi Dollo": ["Assosa", "Gambela", "Gimbi"],
    "Bedele": ["Jimma", "Gore", "Nekemte"],
    "Adama": ["Addis Ababa", "Batu", "Assela", "Matahara"],
    "Matahara": ["Awash", "Adama"],
    "Gore": ["Bedele", "Gambela", "Tepi"],
    "Wolkite": ["Ambo", "Jimma", "Worabe"],
    "Butajira": ["Worabe", "Batu"],
    "Assela": ["Adama", "Assasa"],
    "Batu": ["Adama", "Butajira", "Shashemene"],
    "Dega Habur": ["Jigjiga", "Goba", "Kebri Dehar"],
    "Jimma": ["Wolkite", "Bedele", "Bonga"],
    "Gambela": ["Gore", "Dembi Dollo"],
    "Worabe": ["Butajira", "Wolkite", "Hossana"],
    "Hossana": ["Wolkite", "Butajira", "Sodo"],
    "Tepi": ["Gore", "Mizan Teferi", "Bonga"],
    "Bonga": ["Dawro", "Tepi", "Mizan Teferi", "Jimma"],
    "Mizan Teferi": ["Tepi", "Bonga", "Basketo"],
    "Shashemene": ["Hawassa", "Batu", "Dodola"],
    "Hawassa": ["Shashemene", "Dilla"],
    "Dawro": ["Sodo", "Bonga", "Basketo"],
    "Sodo": ["Hossana", "Arba Minch", "Dawro"],
    "Dodola": ["Assasa", "Bale", "Shashemene"],
    "Assasa": ["Assela", "Dodola"],
    "Bale": ["Dodola", "Goba", "Sof Oumer", "Liben"],
    "Goba": ["Bale", "Dega Habur", "Sof Oumer"],
    "Sof Oumer": ["Kebri Dehar", "Bale", "Goba"],
    "Kebri Dehar": ["Sof Oumer", "Gode", "Werder", "Dega Habur"],
    "Werder": ["Kebri Dehar"],
    "Bench Maji": ["Basketo", "Juba"],
    "Basketo": ["Bench Maji", "Dawro", "Mizan Teferi", "Bonga"],
    "Arba Minch": ["Konso", "Sodo", "Basketo"],
    "Konso": ["Yabello", "Arba Minch"],
    "Dilla": ["Hawassa", "Bule Hora"],
    "Bule Hora": ["Dilla", "Yabello"],
    "Liben": ["Bale"],
    "Gode": ["Kebri Dehar", "Dollo", "Mogadishu"],
    "Dollo": ["Gode"],
    "Juba": ["Bench Maji"],
    "Yabello": ["Konso", "Bule Hora", "Moyale"],
    "Moyale": ["Liben", "Nairobi"],
    "Nairobi": ["Moyale"],
    "Mogadishu": ["Gode"]
}
